services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
      - .docker/nginx/logs/:/var/log/nginx/
      - .:/var/www
    depends_on:
      - app
  
  mariadb:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: test_services
      POSTGRES_USER: test_usr
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  phpmyadmin:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass root

  app:
    container_name: test-app
    build: .docker/php-fpm
    restart: unless-stopped
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: mariadb
      DB_PORT: 5432
      DB_DATABASE: test_services
      DB_USERNAME: test_usr
      DB_PASSWORD: test_password

      REDIS_HOST: redis
      REDIS_PASSWORD: root
      REDIS_PORT: 6379
    depends_on:
      - redis
      - mariadb

volumes:
  pgdata:
